//Exercise #1

# Modify Connectivity Test

When the Mule App starts, a connectivity test runs on the components which are required for connectivity. For instance, a HTTP or FTP connector is needed to connect to an external server. If the connectivity test fails, the default behavior is to log a warning message and continue with the deployment of the Mule app, instead of blocking the deployment.

You can modify this behavior by setting a fixed number of reconnection attempts, to retry connection. If the deployment fails initially and all the reconnection attempts fail, the deployment is forced to fail. 

You can use any of these options to modify the reconnection behavior: 

* Fail Deployment (`failsDeployment`): Forces the deployment to fail if the connection fails, after the configured reconnection attempts are exhausted.
* Reconnect (`reconnect`): Limits the number of reconnection attempts and the interval at which to execute them. For example, a count of 5 reconnection attempts at a `frequency` of every `4000` milliseconds (ms), defaults to 2 reconnection attempts at a frequency of `2000ms`.
* Reconnect Forever (reconnect-forever): Attempts to reconnect at a given interval. For example, every 4000 ms for as long as the app runs, defaults to every 2000 ms. As there is no limit on the number of retries, no value for count is specified.

## Examples 

Example that fails after 5 reconnection attempts are exhausted:

[source,xml]
----
<http:request-config name="HTTP_Request_Config" doc:name="HTTP Request Config">
  <http:request-conection host="https://jsonplaceholder.typicode.com/posts" port="80" >
    <reconnection failsDeployment="true" >
      <reconnect frequency="4000" count="5" />
    </reconnection
  </http:request-connection>
</http:request-config>
----


Example that does not set a limit on the number of reconnection attempts:

[source,xml]
----
<http:request-connection host="https://jsonplaceholder.typicode.com/posts" port="80" >
  <reconnection>
    <reconnect-forever frequency="4000" count=”5”/>
  </reconnection>
</http:request-connectio>
----
